apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: azure-k8s-metrics-adapter-dev
deploy:
  helm:
    releases:
    - name: azure-k8s-metrics-adapter-dev
      chartPath: charts/azure-k8s-metrics-adapter
      values:
        image: azure-k8s-metrics-adapter-dev 
      imageStrategy:
        helm: {}
      overrides:
        image:
          pullPolicy: IfNotPresent
      valuesFiles:
        - local-dev-values.yaml