---
# Source: azure-k8s-metrics-adapter/templates/00-namespace.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: "custom-metrics"

---
# Source: azure-k8s-metrics-adapter/templates/serviceAccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-k8s-metrics-adapter
  namespace: "custom-metrics"
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller

---
# Source: azure-k8s-metrics-adapter/templates/cluster-role.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-k8s-metrics-adapter
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-k8s-metrics-adapter:custom-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
rules:
- apiGroups:
  - custom.metrics.k8s.io
  resources: ["*"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: azure-k8s-metrics-adapter:external-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
rules:
- apiGroups:
  - "external.metrics.k8s.io"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch

---
# Source: azure-k8s-metrics-adapter/templates/cluster-role-binding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter:system:auth-delegator
  namespace: kube-system
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - name: azure-k8s-metrics-adapter
    namespace: "custom-metrics"
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-k8s-metrics-adapter
subjects:
  - name: azure-k8s-metrics-adapter
    namespace: "custom-metrics"
    kind: ServiceAccount
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter:hpa-external-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-k8s-metrics-adapter:external-metrics-reader
subjects:
  - kind: ServiceAccount
    name: horizontal-pod-autoscaler
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: azure-k8s-metrics-adapter:hpa-custom-metrics-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-k8s-metrics-adapter:custom-metrics-reader
subjects:
  - kind: ServiceAccount
    name: horizontal-pod-autoscaler
    namespace: kube-system

---
# Source: azure-k8s-metrics-adapter/templates/role-binding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-k8s-metrics-adapter:extension-apiserver-authentication-reader
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: azure-k8s-metrics-adapter
  namespace: "custom-metrics"

---
# Source: azure-k8s-metrics-adapter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: azure-k8s-metrics-adapter
  namespace: "custom-metrics"
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: azure-k8s-metrics-adapter
    release: azure-k8s-metrics-adapter

---
# Source: azure-k8s-metrics-adapter/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: azure-k8s-metrics-adapter
  namespace: "custom-metrics"
  labels:
    app: azure-k8s-metrics-adapter
    chart: azure-k8s-metrics-adapter-0.1.0
    release: azure-k8s-metrics-adapter
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-k8s-metrics-adapter
      release: azure-k8s-metrics-adapter
  template:
    metadata:
      labels:
        app: azure-k8s-metrics-adapter
        release: azure-k8s-metrics-adapter
    spec:
      serviceAccountName: azure-k8s-metrics-adapter
      containers:
        - name: azure-k8s-metrics-adapter
          image: "mcr.microsoft.com/k8s/metrics/adapter:latest"
          imagePullPolicy: Always
          args:
            - /adapter
            - --secure-port=6443
            - --logtostderr=true
            - --v=2
          ports:
            - name: http
              containerPort: 6443
              protocol: TCP
          env:
          volumeMounts:
            - mountPath: /tmp
              name: temp-vol
          resources:
            {}
            
      volumes:
        - name: temp-vol
          emptyDir: {}

---
# Source: azure-k8s-metrics-adapter/templates/api-service-registration.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  service:
    name: azure-k8s-metrics-adapter
    namespace: custom-metrics
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: azure-k8s-metrics-adapter
    namespace: custom-metrics
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100

---
# Source: azure-k8s-metrics-adapter/templates/secret.yaml

