apiVersion: azure.com/v1alpha1
kind: ExternalMetric
metadata:
  name: example-external-metric-sb
spec:
  azure:
    resourceGroup: sb-external-example
    resourceName: sb-external-ns
    resourceProviderNamespace: Microsoft.ServiceBus
    resourceType: namespaces
  metric:
    metricName: Messages
    aggregation: Total
    filter: EntityName eq 'externalq'